apiVersion: v1
kind: Config
clusters:
- name: "local"
  cluster:
    server: "https://rancher-vinicius.ddns.net/k8s/clusters/local"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ2VENDQ\
      VdPZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQkdNUnd3R2dZRFZRUUtFeE5rZVc1aGJXbGoKY\
      kdsemRHVnVaWEl0YjNKbk1TWXdKQVlEVlFRRERCMWtlVzVoYldsamJHbHpkR1Z1WlhJdFkyRkFNV\
      FkzT0RneApNamsxTmpBZUZ3MHlNekF6TVRReE5qVTFOVFphRncwek16QXpNVEV4TmpVMU5UWmFNR\
      Vl4SERBYUJnTlZCQW9UCkUyUjVibUZ0YVdOc2FYTjBaVzVsY2kxdmNtY3hKakFrQmdOVkJBTU1IV\
      1I1Ym1GdGFXTnNhWE4wWlc1bGNpMWoKWVVBeE5qYzRPREV5T1RVMk1Ga3dFd1lIS29aSXpqMENBU\
      VlJS29aSXpqMERBUWNEUWdBRTJQTCtWNXFYQVZ1Sgo0UDdoSzYxRWFwNzdndkNXSlNaZHVGWHV5L\
      1NxTzlkY3RDZ0hldGo3dUIrUHFnRkhIZnBlbmRab2htSUNqTXFHCm1heUlKNlcwMzZOQ01FQXdEZ\
      1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWUQKVlIwT0JCWUVGQ\
      2wyL00vb1pTSXNuUTJMQVRDM2lXbTRHZ3dPTUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSVFEUQp5d\
      1Y2a3kzTDBQRWhJdVdjc1hlZmFHUFJKK0o5aVZoSVFBSERoR3VTVndJZ1RnYllaSUQ5NEdJLzdWU\
      Hh6RVJqClB1ZlBMMGZmRGI3akxOZnEycExjMUprPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t"

users:
- name: "local"
  user:
    token: "kubeconfig-user-s6fqwz75gg:9dxqhcss7drf7zcrwqr8h9pbvthldjtkfctz52mwbcxptf94d2mcfz"


contexts:
- name: "local"
  context:
    user: "local"
    cluster: "local"

current-context: "local"

