#!/usr/bin/python3
from kubernetes import client, config
print("content-type: text/html")
print("")

print('''
    <html>
    <head><meta http-equiv="refresh" content="3"></head>
    <body>
    <h2>Desafio com script python</h2>
    <ul>
    ''')

# Estabelece a conexão com o cluster
config.load_incluster_config()

api = client.CoreV1Api()

namespaces = api.list_namespace().items
    
for namespace in namespaces:
    print(f"<li>{ namespace.metadata.name }</li>")

print(''' 
    </ul>
    </body>
    </html>
    ''')  